const coursesData = [
  {
    key: 1,
    course_name: "The Complete Angular Course: Beginner to Advanced",
    instructor: "Nayem Hossain",
    Category: "javascript framework",
    course_time: "6 Months",
    price: 99,
    rating: "4.7",
    total_lacture: "65",
    level: "advanced",
    img: "./course images/angular.jpg",
    description:
      "The most comprehensive Angular 4 (Angular 2+) course. Build a real e-commerce app with Angular, Firebase and Bootstrap 4",
  },
  {
    key: 2,
    course_name: "AWS Certified Solutions Architect - Associate 2021",
    instructor: "Stephane Maarek",
    Category: "frontend library",
    course_time: "3 Months",
    price: 19,
    rating: "4.7",
    total_lacture: "17",
    level: "basic to advanced",
    img: "./course images/aws essentials.jpg",
    description:
      "Pass the AWS Certified Advanced Networking Specialty Certification ANS-C00. Taught by an AWS Networking Expert!",
  },
  {
    key: 3,
    course_name: "JavaScript Algorithms and Data Structures Masterclass",
    instructor: "Colt Steele",
    Category: "data structure",
    course_time: "3.5 Months",
    price: 55,
    rating: "4.7",
    total_lacture: "37",
    level: "basic",
    img: "./course images/data structure & algorithm.jpg",
    description: "The Missing Computer Science and Coding Interview Bootcamp",
  },
  {
    key: 3,
    course_name: "Django Full Stack Web Developer Bootcamp",
    instructor: "Nayem Hossain",
    Category: "python framework",
    course_time: "4 Months",
    price: 79,
    rating: "4.5",
    total_lacture: "28",
    level: "basic to intermediate",
    img: "./course images/django.jpg",
    description: "Learn to build awesome websites with Python & Django!",
  },
  {
    key: 4,
    course_name: "Docker Mastery: with Kubernetes +Swarm from a Docker Captain",
    instructor: "Bret Fisher",
    Category: "plugin",
    course_time: "3 Months",
    price: 44,
    rating: "4.5",
    total_lacture: "22",
    level: "intermediate",
    img: "./course images/docker.jpg",
    description:
      "Build, test, deploy containers with the best mega-course on Docker, Kubernetes, Compose, Swarm and Registry using DevOps",
  },
  {
    key: 5,
    course_name: "The essential guide to Firebase with React.",
    instructor: "Bret Fisher",
    Category: "database & js library",
    course_time: "4 Months",
    price: 45,
    rating: "3.9",
    total_lacture: "24",
    level: "advanced",
    img: "./course images/firebase with react.jpg",
    description: "Create modern app using modern technologies",
  },
  {
    key: 6,
    course_name: "Flutter & Dart - The Complete Guide [2021 Edition]",
    instructor: "Academind by Maximilian Schwarzmüller",
    Category: "mobile app framework",
    course_time: "6 Months",
    price: 85,
    rating: "4.9",
    total_lacture: "34",
    level: "intermediate",
    img: "./course images/flutter.jpg",
    description:
      "A Complete Guide to the Flutter SDK & Flutter Framework for building native iOS and Android apps",
  },
  {
    key: 7,
    course_name: "MongoDB - The Complete Developer's Guide 2021",
    instructor: "Academind by Maximilian Schwarzmüller",
    Category: "database",
    course_time: "5 Months",
    price: 77,
    rating: "4.9",
    total_lacture: "38",
    level: "intermediate",
    img: "./course images/mongodb.jpg",
    description:
      "Master MongoDB Development for Web & Mobile Apps. CRUD Operations, Indexes, Aggregation Framework - All about MongoDB!",
  },
  {
    key: 8,
    course_name: "MySQL Bootcamp: Go from SQL Beginner to Expert",
    instructor: "Colt Steele",
    Category: "database",
    course_time: "3 Months",
    price: 70,
    rating: "4.3",
    total_lacture: "33",
    level: "basic to intermediate",
    img: "./course images/mySQL.jpg",
    description:
      "Become an In-demand SQL Master by creating complex databases and building reports through real-world projects",
  },
  {
    key: 9,
    course_name: "Node.js, Express, MongoDB Bootcamp 2021 - with Real Projects",
    instructor: "Ghulam Abbas",
    Category: "js runtime",
    course_time: "5 Months",
    price: 67,
    rating: "4.9",
    total_lacture: "55",
    level: "intermediate",
    img: "./course images/mongodb.jpg",
    description:
      "Master Node, Express & MongoDB by building real-world apps with Authentication, File Uploads, WebScrapping, Deployment..",
  },
  {
    key: 10,
    course_name: "React with Redux and Hook",
    instructor: "Nayem Hossain",
    Category: "frontend library",
    course_time: "3 Months",
    price: "19",
    rating: "4.7",
    total_lacture: "17",
    level: "intermediate",
    img: "./course images/react with hook and redux.jpg",
    description: "Improve your understanding of React",
  },
];
